apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quality-inspection
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ayushtestacr.azurecr.io/helm/webfrontend
    chart: webfrontend
    targetRevision: 0.1.0
    helm:
      releaseName: 1e4700c3a71ce2255bab7f18ca73e5552982fd82
      values: |
          Name: quality-inspection
          batchSize: 500
          temperature: 40
          defectThreshold: 1.5
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
